### ISSUE TITLE
Enable webcam and microphone on startup

### ISSUE THREAD

**Issue by krisalay** [GoogleChrome/chrome-launcher#103]
I want to record the screen and audio using chrome-launcher. So, how do I auto enable microphone and webcam?

**Comment by patrickhulce** [comment]
This question seems to be well beyond the scope of chrome-launcher, which is just responsible for opening Chrome. There are multiple ways of doing programmatic screen/webcam recording through [other](https://trac.ffmpeg.org/wiki/Capture/Webcam) [means](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-startScreencast) but they're quite unrelated to *launching* Chrome :)

**Comment by krisalay** [comment]
@patrickhulce 
Thank you. I will look into other means for my requirement.
