### ISSUE TITLE
Support q: Pipe html to chrome launcher

### ISSUE THREAD

**Issue by ORESoftware** [GoogleChrome/chrome-launcher#106]
This works for me:

```bash
echo '<h1>hello, world</h1>' | /Applications/Firefox.app/Contents/MacOS/firefox /dev/fd/0
```

I am looking for a way to pipe html to Chrome instead of Firefox.

Is there a way to do that using this lib?

**Comment by ORESoftware** [comment]
Still looking for answers to this one if anyone is out there, thx

**Comment by paulirish** [comment]
nope this isn't supported.

the best we could do is turn a string into a data-uri and pass that in. I'm pretty sure there are length limits though, so i'm not sure it's worth it.

the projects ive seen that do this (`vzi` and `bcat`) both use a file and load that file (from file:// or localhost).
