### ISSUE TITLE
Temp directory makes assumption about WSL paths

### ISSUE THREAD

**Issue by vcsjones** [GoogleChrome/chrome-launcher#110]
WSL starting in Windows 1803 allows file systems to be mounted in places other than `/mnt` by configuration.

I've taken to mounting them simply in `/` so that I can access `/c/window-stuff`. For example:

```
[automount]
enabled = true
root = /
```

The causes the launcher to fail to make a temp directory due to this line:

https://github.com/GoogleChrome/chrome-launcher/blob/dd5fdd490d147afdabc1874a822b72b4d9ede32b/src/utils.ts#L88

It makes an assumption about where the windows file system is mounted.

**Comment by vcsjones** [comment]
I'm happy to make a pull request to address the issue if anyone has a good idea on how to address this.

**Comment by vcsjones** [comment]
Frankly I would also be happy if there was no specialized code paths for WSL at all. I expected it to use the `chromium-browser` package in the first place, not try and use the one from Windows.

**Comment by paulirish** [comment]
yah would be happy to get a PR for this.
