### ISSUE TITLE
Connecting Puppeteer to a Chrome-Launcher instance.

### ISSUE THREAD

**Issue by rlpham** [GoogleChrome/chrome-launcher#114]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: v1.5.0
* Platform / OS version: Mac OS X El Capitan v10.11.6
* URLs (if applicable):
* Node.js version: v10.2.1

**What steps will reproduce the problem?**
1. 
const chromeLauncher = require('chrome-launcher');
const puppeteer = require('puppeteer');
const request = require('request');
const util = require('util');

(async() => {

const chrome = await chromeLauncher.launch({
  startingUrl: 'http://www.google.com'
});

const resp = await util.promisify(request)(`http://localhost:${chrome.port}/json/version`);
const {webSocketDebuggerUrl} = JSON.parse(resp.body);
const browser = await puppeteer.connect({
  browserWSEndpoint: webSocketDebuggerUrl
});
const page = browser.newPage();

})();

**What is the expected result?**
Puppeteer connects with the chrome launcher instance and creates a new page.

**What happens instead?**
Stays on starting url (google.com) unsure if it is actually connected to it or not.

**Comment by paulirish** [comment]
documented now: https://github.com/GoogleChrome/lighthouse/blob/master/docs/puppeteer.md
