### ISSUE TITLE
Killing launched chrome instance in mocha afterEach

### ISSUE THREAD

**Issue by mfestrada** [GoogleChrome/chrome-launcher#120]
Hi there, 

I have some integration-level tests of a web app that I need to use a headless chrome instance for, and I'm using mocha as a testing framework.  I'd like to use this package for opening/closing the browser in each tests' setup/teardown, but I can't reconcile how to handle the teardown of the browser.  

Say that I have some mocha tests that look like:

```javascript
const chromeLauncher = require('chrome-launcher');

describe('Foo', function() {
  beforeEach(async function() {
    // this part is obviously how I'd launch a browser instance for each test
    chromeLauncher.launch({
      startingUrl: 'https://example.com',
      chromeFlags: ['--headless', '--disable-gpu']
    });
  });

  afterEach(async function() {
    // not sure how to kill the browser I've launched here
  });

  it('Does bar', async function() {
    // testing code that uses chrome
  });
});

```

I don't know how I'm supposed to kill the process in an ```afterEach``` teardown.  I was wondering if someone could point me in the right direction for what I'm trying to do?  Thanks in advance.

**Comment by patrickhulce** [comment]
You'll want to hang on to the chrome instance that's returned

```js
describe('Foo', function() {
  let chrome

  beforeEach(async function() {
    // this part is obviously how I'd launch a browser instance for each test
    chrome = await chromeLauncher.launch({
      startingUrl: 'https://example.com',
      chromeFlags: ['--headless', '--disable-gpu']
    });
  });

  afterEach(async function() {
    // not sure how to kill the browser I've launched here
    await chrome.kill()
  });

  it('Does bar', async function() {
    // testing code that uses chrome
  });
});

**Comment by patrickhulce** [comment]
Also @mfestrada you might want to look into https://github.com/GoogleChrome/puppeteer if you haven't already. It's got a lot of examples and great API to work with chrome for testing.

**Comment by mfestrada** [comment]
@patrickhulce Thank you for your help!!  Sorry to open an issue for something so simple. I've looked into puppeteer, but I had to opt for chrome-remote-interface for some even-lower level capabilities.  All of this headless work you folks are doing is awesome, cheers to you all!
