### ISSUE TITLE
How can i launch it with a extension enabled?

### ISSUE THREAD

**Issue by impraveensingh** [GoogleChrome/chrome-launcher#130]
Is there any way to include the external extension?

**Comment by patrickhulce** [comment]
You'll want to launch chrome with a user profile (using the `userDataDir` option) that has the extension installed and use the `enableExtensions` option. 

https://github.com/GoogleChrome/chrome-launcher#launchopts

**Comment by paulirish** [comment]
There's a new option to handle this case: https://github.com/GoogleChrome/chrome-launcher#launching-with-support-for-extensions-and-audio
