### ISSUE TITLE
Opens multiple chromium browser even though only one instance of chrome is invoke

### ISSUE THREAD

**Issue by EnlightenMeee** [GoogleChrome/chrome-launcher#131]
![image](https://user-images.githubusercontent.com/45029535/48993494-dd8a5480-f178-11e8-8266-bccff0f103e3.png)

every time i call chrome-launch in my puppeteer-lighthouse project it always opens multiple chromium process.

![image](https://user-images.githubusercontent.com/45029535/48993528-090d3f00-f179-11e8-8488-f6043c5142e4.png)

**Comment by patrickhulce** [comment]
@EnlightenMeee puppeteer already launches Chrome for you by default, so you wouldn't need chrome-launcher, are you sure you're using them together properly?
