### ISSUE TITLE
Launch chrome with un-muted audio

### ISSUE THREAD

**Issue by DusanBrejka** [GoogleChrome/chrome-launcher#135]
Is there a simple way to launch Chrome without `--mute-audio` flag?
Or is it possible to clear out all default flags without forking the project and doing it manually?

Seems like there's no option right now other than reverting to old version
#65 #134 #28 #38 #70 #122 #124

**Comment by DusanBrejka** [comment]
Until someone comes up with a viable solution, this is the only thing I could do as I wasn't able to properly build and test it due to type errors... I feel ashamed as a developer but whatever, it gets the shit done :smiley: 


```javascript
// PLEASE COME UP WITH A BETTER SOLUTION
// DON'T USE IT IN PRODUCTION

const _fs = require('fs');
const _path = require('path');

let clResolve = require.resolve('chrome-launcher');
if(clResolve) {
    clResolve = _path.join(_path.dirname(clResolve), 'flags.js');
    if(_fs.existsSync(clResolve)) {
        let content = _fs.readFileSync(clResolve, 'utf8');
        let newContent = content.replace(/^(\s+'--mute-audio')/gm, '//$1');
        if(content !== newContent) _fs.writeFileSync(clResolve, newContent, 'utf8');
    }
}

let chrome = require('chrome-launcher');
chrome.launch({ ... }); // Chrome will be launched without --mute-audio
```


Chrome-launcher contributors, please merge

**Comment by glebmachine** [comment]
Could you please add ability to disable default flags?

**Comment by DusanBrejka** [comment]
> 
> 
> Could you please add ability to disable default flags?

Well technically you can update the regex on 12th line of my code to match all uncommented lines:
```javascript
let newContent = content.replace(/^(\s+'--[\S-]+')/gm, '//$1');
```
or just replace the whole flags.js file... yeah, I know, I know - but it gets shit done

But anyway, this basic functionality - to disable default flags must definitely become a part of the library itself asap...

**Comment by glebmachine** [comment]
I've clear FLAGS and create patch with patch-package.

Looks very strange, that i'm unable to remove default flags

**Comment by crislin2046** [comment]
You can use the option:   ignoreDefaultFlags: true

**Comment by paulirish** [comment]
> ignoreDefaultFlags

exactly! 

documented now: https://github.com/GoogleChrome/chrome-launcher#launching-with-support-for-extensions-and-audio
