### ISSUE TITLE
Question: How to open a page behind basic authentication? #1418

### ISSUE THREAD

**Issue by hazemhagrass** [GoogleChrome/chrome-launcher#143]
I'm wondering how to open a page using chrome-luncher behind basic authentication!
In other words, how to pass authentication headers to chrome-luncher while lunching chrome or opening a certain page?

**Comment by tk26** [comment]
You'll need to get a token and pass in through the url. Something like - 
https://www.website.com/?Authorization=Bearer%20<token>.

**Comment by paulirish** [comment]
documented now: https://github.com/GoogleChrome/lighthouse/blob/master/docs/recipes/auth/README.md and https://github.com/GoogleChrome/lighthouse/blob/master/docs/puppeteer.md
