### ISSUE TITLE
Support for macOS Catalina

### ISSUE THREAD

**Issue by m7r** [GoogleChrome/chrome-launcher#146]
chrome-finder.js has problems to find the path of the installed Chrome app.

It seems the output of lsregister has changed.

macOS 10.15 Beta (19A471t)

**Comment by patrickhulce** [comment]
Thanks for being an early tester for us @m7r! Do you happen to know at what path Chrome *is* installed on Catalina?

**Comment by jHoldroyd** [comment]
It's not that it's moved, it's just the output of lsregister has changed and it seems that there is now a hex string at the end of the line for path:

`path:               /Applications/Google Chrome.app (0xa5c)`

**Comment by patrickhulce** [comment]
Ah gotcha, thanks for the extra info!
