### ISSUE TITLE
Add Wsl 2 support

### ISSUE THREAD

**Issue by KyivJunta** [GoogleChrome/chrome-launcher#150]
WSL 2 is not detected by the current `is-wsl` version. Please update it to the latest (`2.1.0`) version.

**Comment by KyivJunta** [comment]
`is-wsl` drops Node 6 support - do we need it in 2019?

**Comment by KyivJunta** [comment]
#152:
- updates `is-wsl` to the current version
- drops Node 6 support
- adds Node 10/12 support

**Comment by brendankenny** [comment]
closed in #152
