### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by KyivJunta** [GoogleChrome/chrome-launcher#153]
When can we expect new release with updated `is-wsl` dependency? Dependents, such as `lighthouse` would benefit from it.

**Comment by patrickhulce** [comment]
It's a breaking change so we should probably batch it with the other breaking changes we need to get in ASAP (#124)

**Comment by dylang** [comment]
Looks like it's been 6 months since we've published a new version of this module. 

Features like `.killAll` are not in the current release.

_This comment is to help others trying to figure out why stuff in the README may not work as expected._

**Comment by paulirish** [comment]
v0.13.0 published today.

changelog: https://github.com/GoogleChrome/chrome-launcher/blob/master/changelog.md#v0130-thu-feb-27-2020
