### ISSUE TITLE
Xvfb support for chrome-launcher

### ISSUE THREAD

**Issue by dkajtoch** [GoogleChrome/chrome-launcher#156]
Is there a way to "inject" a custom shell command before chrome launcher. I would like to open chrome with xvfb and the kill it. As far as I know (I maybe wrong) you are spawning a child process from nodejs with chrome. In principle I could add there xvfb-run, but I would have change the whole package. Is there a simpler way to do that?

**Comment by patrickhulce** [comment]
Are you not able to start xvfb and set the DISPLAY env variable for the process in which `chrome-launcher` is running?

This is how we run in travis for example

https://github.com/GoogleChrome/chrome-launcher/blob/57e18181ac84090fd4ea240a99c644c06343c4a0/.travis.yml#L17-L21

**Comment by dkajtoch** [comment]
That is indeed very simple :)

**Comment by patrickhulce** [comment]
Cool I'll go ahead and mark this as closed then, but feel free to come back if you still feel there's functionality that needs to be added.
