### ISSUE TITLE
Final TODOs of chrome-launcher repo split

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/chrome-launcher#16]
- [x] update repo in package.json
  - [x] publish new version to NPM so links are updated.
    - [x] update `curl` line in [readme](https://github.com/GoogleChrome/chrome-launcher/blob/6b01a049f577340c470937af24aed881f30c98fa/README.md) to use tagged URL instead.
- [x] add travis to this repo
- [x] add appveyor to repo
- [x] move [download-chrome.sh](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/scripts/download-chrome.sh) from LH to launcher (and update launcher readme)
- [x] remove code from lighthouse
   - [x] keep a stub readme.md in place to forward people
- [x] manually port over any pending PRs, branches.

Anything else?

**Comment by brendankenny** [comment]
A Lighthouse run in the chrome-launcher tests? Kind of favoring Lighthouse with that, but it would increase confidence in any chrome-launcher changes

**Comment by patrickhulce** [comment]
shall we add a stub require'able file that `module.exports = require('chrome-launcher')` until we do a major version bump at least?

**Comment by paulirish** [comment]
@patrickhulce (handling people that use `lighthouse/chrome-launcher/index.js`) yes for sure.

@brendankenny yes andor puppeteer script. sg

**Comment by paulirish** [comment]
this will be fixed when https://github.com/GoogleChrome/lighthouse/pull/3410 lands
