### ISSUE TITLE
Is it possible to run multiple headless chrome instances?

### ISSUE THREAD

**Issue by LeMoussel** [GoogleChrome/chrome-launcher#163]
I need to run multiple headless chrome instances in parallel in order to efficiently generate output by processing lighthouse on different chrome port.

But executing the following method, I got only one instance of chrome 
```
function launchChrome() {
  return chromeLauncher.launch({
    autoSelectChrome: true,
    chromeFlags: [
      '--disable-gpu',
      '--no-sandbox',
    ],
    logLevel: 'verbose',
  });
}

(async () => {
  const browser1 = await launchChrome();
  console.log(`browser1 port: ${browser1.port}`);
  
  const browser2 = await TlaunchChrome();
  console.log(`browser2 port: ${browser2.port}`);
})().catch(e => {
  console.error(e);
  process.exit(1);
});
```

> Thu, 18 Jul 2019 09:50:52 GMT ChromeLauncher:verbose created D:\Temp\AppData\Local\Temp\lighthouse.60468161
> Thu, 18 Jul 2019 09:50:52 GMT ChromeLauncher:verbose Launching with command:
> "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --disable-translate --disable-extensions --disable-background-networking --disable-sync --metrics-recording-only --disable-default-apps --mute-audio --no-first-run --remote-debugging-port=61329 --user-data-dir=D:\Temp\AppData\Local\Temp\lighthouse.60468161 --disable-gpu --no-sandbox about:blank
> Thu, 18 Jul 2019 09:50:52 GMT ChromeLauncher:verbose Chrome running with pid 2800 on port 61329.
> Thu, 18 Jul 2019 09:50:52 GMT ChromeLauncher Waiting for browser.
> Thu, 18 Jul 2019 09:50:52 GMT ChromeLauncher Waiting for browser...
> Thu, 18 Jul 2019 09:50:53 GMT ChromeLauncher Waiting for browser...√
> browser1 port: 61329

**Comment by patrickhulce** [comment]
it looks like we're missing some logs @LeMoussel can you share the logs of what happened after

`browser1 port: 61329`?

**Comment by LeMoussel** [comment]
The logs are complete. There are no other displays. Among other things, no display of `browser2 port: ...`

**Comment by patrickhulce** [comment]
Did you copy your script verbatim? The `TlaunchChrome()` typo prevents the script from continuing which would explain the lack of logs. Fixing the typo yields 2 separate Chrome instances.

```
  ChromeLauncher:verbose created /var/folders/wx/hgwkvrds5s55g0snjr41ffm80000gn/T/lighthouse.XXXXXXX.0i6NY3BT +0ms
  ChromeLauncher:verbose Launching with command:
  ChromeLauncher:verbose "/Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary" --disable-translate --disable-extensions --disable-background-networking --safebrowsing-disable-auto-update --disable-sync --metrics-recording-only --disable-default-apps --mute-audio --no-first-run --remote-debugging-port=54074 --user-data-dir=/var/folders/wx/hgwkvrds5s55g0snjr41ffm80000gn/T/lighthouse.XXXXXXX.0i6NY3BT --disable-gpu --no-sandbox about:blank +4ms
  ChromeLauncher:verbose Chrome running with pid 36467 on port 54074. +3ms
  ChromeLauncher Waiting for browser. +0ms
  ChromeLauncher Waiting for browser... +0ms
  ChromeLauncher Waiting for browser..... +513ms
  ChromeLauncher Waiting for browser.....✓ +2ms
browser1 port: 54074
  ChromeLauncher:verbose created /var/folders/wx/hgwkvrds5s55g0snjr41ffm80000gn/T/lighthouse.XXXXXXX.WPynrw0x +485ms
  ChromeLauncher:verbose Launching with command:
  ChromeLauncher:verbose "/Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary" --disable-translate --disable-extensions --disable-background-networking --safebrowsing-disable-auto-update --disable-sync --metrics-recording-only --disable-default-apps --mute-audio --no-first-run --remote-debugging-port=54087 --user-data-dir=/var/folders/wx/hgwkvrds5s55g0snjr41ffm80000gn/T/lighthouse.XXXXXXX.WPynrw0x --disable-gpu --no-sandbox about:blank +1ms
  ChromeLauncher:verbose Chrome running with pid 36489 on port 54087. +3ms
  ChromeLauncher Waiting for browser. +0ms
  ChromeLauncher Waiting for browser... +1ms
  ChromeLauncher Waiting for browser..... +502ms
  ChromeLauncher Waiting for browser.....✓ +1ms
browser2 port: 54087

**Comment by LeMoussel** [comment]
You're right! So much for my typo error. With all my apologies.
