### ISSUE TITLE
defaultFlags function not documented correctly

### ISSUE THREAD

**Issue by PeterPorzuczek** [GoogleChrome/chrome-launcher#168]
`defaultFlags` function is not working.

I attach screens
![Code_yvWT8gjwSC](https://user-images.githubusercontent.com/24259570/64408772-d8ebb880-d087-11e9-8815-78fbbb71beb8.png)
![Code_fWvpru2PCy](https://user-images.githubusercontent.com/24259570/64408791-e30db700-d087-11e9-93b5-cae2bada78ee.png)
![Code_18uYqCH6G5](https://user-images.githubusercontent.com/24259570/64408799-e86b0180-d087-11e9-8563-f287759a6460.png)

**Comment by PeterPorzuczek** [comment]
It looks like the default instance is nont exported properly so in order to get to the flags we have to use `chromeLauncher.Launcher.defaultFlags ()`
![Code_5osUBUikF8](https://user-images.githubusercontent.com/24259570/64415897-70f09e80-d096-11e9-9ed4-21c7ccc4b448.png)

**Comment by patrickhulce** [comment]
Thanks for filing @PeterPorzuczek the documentation needs to be updated!

**Comment by PeterPorzuczek** [comment]
Maybe we should update the exports because the api proposed in the documentation is more readable to me than `chromeLauncher.Launcher.defaultFlags()` but the community should decide on this issue solution.
