### ISSUE TITLE
Launching chrome with --version doesn't output the version

### ISSUE THREAD

**Issue by pedalshoe** [GoogleChrome/chrome-launcher#173]
We are trying to get the version of chrome that is being launched. 

we are trying this code - is there an example of this - from the command line you can start chrome with --version and get the following output in the terminal and Chrome exits:
**Google Chrome 77.0.3865.75** 

Is there a way to do this with chrome-launcher

`

console.info(process.platform);

ChromeLauncher.launch({
  port: 8222,
  chromeFlags: [ "--version", "--headless", "--disable-gpu"  ],
  startingUrl: "chrome://version/",                                              
 logLevel: "verbose"
}).then(chrome => {
  console.log(`Chrome debugging port running on ${chrome.port} pid=${chrome.pid} envVars=${chrome.envVars()}` );
});

`

**Comment by brendankenny** [comment]
Someone else can chime in if they know a nice way, but I can't imagine this would be pretty.

Maybe we could have the instance returned by `launch()` include a `version` property, though? @pedalshoe would you be interested in making that change?

**Comment by brendankenny** [comment]
> Maybe we could have the instance returned by launch() include a version property, though? @pedalshoe would you be interested in making that change?

or if the only way to get that is through running Chrome with `--version`, we probably won't want to pay that price on every launch. We could instead have a separate `ChromeLauncher.version()` => `Promise<versionString>` function? Open to other ideas, too :)

**Comment by paulirish** [comment]
i think the most straightforward way is to launch and then use the protocol to call [Browser.getVersion](https://chromedevtools.github.io/devtools-protocol/tot/Browser#method-getVersion)

**Comment by pedalshoe** [comment]
Sorry for the delay - Getting back to this. If I set the userDataDir (to get a predictable location) I see the "version" output in the userDataDir in the chrome-out.log file.
But i get
  ChromeLauncher Waiting for browser. +0ms
  ChromeLauncher Waiting for browser... +0ms
  ChromeLauncher Waiting for browser..... +509ms
at the end - I need to kill ChromeLauncher now and just parse the output file.
How do I just Kill ChromeLauncher after chrome dumped the version in chrome-out.log?
