### ISSUE TITLE
"Process could not be terminated" error is thrown on Windows

### ISSUE THREAD

**Issue by onderceylan** [GoogleChrome/chrome-launcher#178]
First of all, thanks for this awesome library! I use it together with puppeteer-core to avoid chromium installs if Chrome exists on users system, in the library that I maintain: https://github.com/onderceylan/pwa-asset-generator

I'm getting the following error on Windows, after calling `chrome.kill()`. 

```
ERROR: The process with PID 12345 (child process of PID 1234) could not be terminated.
Reason: There is no running instance of the task.
```

I see 2 issues with this;

1. Not sure why but sometimes this error occur and sometimes not. Ideally, I hope the root cause of this can be found and fixed.

2. Second issue is, this error is being logged to the console directly, and logLevel setting is not respected when this error is thrown. Ideally, it should be logged based on logLevel setting.

I hope it's possible to get this issue fixed. If not, I'd love to go for the second option as this issue logs an unnecessary output for my CLI lib at the moment.

**Comment by patrickhulce** [comment]
Thanks for filing! 

1. That error typically means that Chrome has already died, so there is nothing left to be killed. If you do not really care if Chrome is already dead, then you should be able to safely ignore rejections from `.kill()`
2. Nice catch! It's being output directly to stderr by the taskkill command in our `execSync`. If anyone is interested in a PR, we should just need to throw `{stdio: 'pipe'}` on https://github.com/GoogleChrome/chrome-launcher/blob/2e829c7de52220b0e5df1deab37bde2e89245ea1/src/chrome-launcher.ts#L335 (it's pipe by default but nodejs also outputs stderr to parent stderr if you don't manually specify `stdio`

**Comment by onderceylan** [comment]
Thanks for thorough instructions @patrickhulce. I will create a PR to improve the logging soon.

**Comment by PPInfy** [comment]
I am getting the following error after applying your changes as well.

Error: Chrome could not be killed Command failed: taskkill /pid 10576 /T /F
ERROR: The process with PID 11820 (child process of PID 10576) could not be term
inated.
Reason: The operation attempted is not supported.

    at Promise (D:\TEST\TestNPM\LatestCode\is-website-vulnerable-master\node_mod
ules\chrome-launcher\dist\chrome-launcher.js:259:28)
    at new Promise (<anonymous>)
    at Launcher.kill (D:\TEST\TestNPM\LatestCode\is-website-vulnerable-master\no
de_modules\chrome-launcher\dist\chrome-launcher.js:241:16)
    at Object.<anonymous> (D:\TEST\TestNPM\LatestCode\is-website-vulnerable-mast
er\node_modules\chrome-launcher\dist\chrome-launcher.js:58:29)
    at Generator.next (<anonymous>)
    at D:\TEST\TestNPM\LatestCode\is-website-vulnerable-master\node_modules\chro
me-launcher\dist\chrome-launcher.js:12:71
    at new Promise (<anonymous>)
    at __awaiter (D:\TEST\TestNPM\LatestCode\is-website-vulnerable-master\node_m
odules\chrome-launcher\dist\chrome-launcher.js:8:12)
    at Object.kill (D:\TEST\TestNPM\LatestCode\is-website-vulnerable-master\node
_modules\chrome-launcher\dist\chrome-launcher.js:53:28)
    at Audit.scanUrl (D:\TEST\TestNPM\LatestCode\is-website-vulnerable-master\sr
c\Audit.js:81:26)

Usage:
  is-website-vulnerable https://www.example.com

**Comment by PPInfy** [comment]
However trying this code worked

setTimeout( () => {
								execSync(`taskkill /pid ${this.chrome.pid} /T /F`)}
							,500);
