### ISSUE TITLE
async killAll function for all launched broswers?

### ISSUE THREAD

**Issue by crislin2046** [GoogleChrome/chrome-launcher#185]
As discussed in #184 there can be conflicts between asynchronous SIGINT handlers registered in different parts of a program, leading to one handler calling process.exit before all work from all handlers is complete. 

If a Promise returning `killAll` function was exposed, this would provide a way to wait for all browsers to close before calling `process.exit`, and could be combined with `handleSIGINT: false` to stop c-l from calling `process.exit`.

Effectively this would give control over when process.exit is called, and also provide a simple async API for closing browsers, without you as a user of c-l needing to care about how that cleanup was done, nor doing it yourself, only needing to care about when you want to do it, then asking c-l to do its own cleanup for you by instructing it to with `killAll`.

**Comment by patrickhulce** [comment]
`killAll` sounds great to me :)

**Comment by crislin2046** [comment]
Can you assign me as a reminder for me to create a PR?
