### ISSUE TITLE
Directory "\Default" is added to userDataDir 

### ISSUE THREAD

**Issue by jsnico** [GoogleChrome/chrome-launcher#190]
Hello,

On Windows 10 I want to use a profile directory "C:/Users/nicol/AppData/Local/Google/Chrome/User Data/Profile 3" but instead "C:\Users\nicol\AppData\Local\Google\Chrome\User Data\Profile 3\Default" is used by Chrome Launcher with the code as follows :

```js
const ChromeLauncher = require("chrome-launcher")

ChromeLauncher.launch({
  logLevel: "verbose",
  userDataDir: "C:/Users/nicol/AppData/Local/Google/Chrome/User Data/Profile 3",
  startingUrl: "https://google.com"
}).then(chrome => {
  console.log(`Chrome debugging port running on ${chrome.port}`)
})
````

The Chrome Launcher uses this directory :
"C:/Users/nicol/AppData/Local/Google/Chrome/User Data/Profile 3/Default"

Here is the log with logLevel set to "verbose":
```
Fri, 06 Mar 2020 15:11:56 GMT ChromeLauncher:verbose created C:/Users/nicol/AppData/Local/Google/Chrome/User Data/Profile 3
Fri, 06 Mar 2020 15:11:56 GMT ChromeLauncher:verbose Launching with command:
"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --disable-features=TranslateUI --disable-extensions --disable-component-extensions-with-background-pages --disable-background-networking --disable-sync --metrics-recording-only --disable-default-apps --mute-audio --no-default-browser-check --no-first-run --disable-backgrounding-occluded-windows --disable-renderer-backgrounding --disable-background-timer-throttling --remote-debugging-port=57300 --user-data-dir=C:/Users/nicol/AppData/Local/Google/Chrome/User Data/Profile 3 https://google.com
Fri, 06 Mar 2020 15:11:56 GMT ChromeLauncher:verbose Chrome running with pid 18960 on port 57300.
Fri, 06 Mar 2020 15:11:56 GMT ChromeLauncher Waiting for browser.
Fri, 06 Mar 2020 15:11:56 GMT ChromeLauncher Waiting for browser...
Chrome debugging port running on 57300
Fri, 06 Mar 2020 15:11:57 GMT ChromeLauncher Waiting for browser...√
```

With url "chrome://version/" the profile directory is "C:\Users\nicol\AppData\Local\Google\Chrome\User Data\Profile 3\Default"

For information:
Node v12.13.1
Chrome Launcher v0.13.0

**Comment by paulirish** [comment]
ah. so userDataDir is the parent folder of specific user profiles.

it's much easier to just work with default profiles and not try to use secondary profiles within a userdatadir

#172 the same issue as this.. in there Vikram figured out a workaround but it is rather brittle, IMO.  but please take a look

**Comment by jsnico** [comment]
Thanks for the reply.

I've used Puppeteer which is very great project but Puppeteer is detected by Datadome in headless true or false mode even with modifications of the http header.
The fix of http header was working at the begining but Datadome improve the detection of the use of Chromium browser with Puppeteer.

So I've developped my own solution with C++ but I don't feel very comfortable with this language and so far, I prefer Javascript and node.js.

In my case I could work with setting "C:/Users/nicol/AppData/Local/Google/Chrome/User Data/Profile xxx" which is modified to "C:/Users/nicol/AppData/Local/Google/Chrome/User Data/Profile xxx/Default" by Chrome Launcher
When you understand how it's modified you could deal with.

But the documentation of userDataDir is :

>   // (optional) Chrome profile path to use, if set to `false` then the default profile will be used.
>   // By default, a fresh Chrome profile will be created
>   userDataDir: string | boolean;

  
So when :
- userDataDir is not set -> Chrome Launcher create a fresh profile
- userDataDir set to true you get -> message: 'userDataDir must be false or a path.', code: 'ERR_LAUNCHER_INVALID_USER_DATA_DIRECTORY'
- userDataDir set to false -> Chrome Launcher use the Default profile which is ok for me
- userDataDir set to "C:/Users/nicol/AppData/Local/Google/Chrome/User Data/Profile xxx" for me it shouldn't add "/Default"
