### ISSUE TITLE
Separately or export getInstallations logic

### ISSUE THREAD

**Issue by LarsDenBakker** [GoogleChrome/chrome-launcher#206]
I want to use the `getInstallations` function to use the locally installed Chrome with `puppeteer-core`. It would be great if this logic could be shipped in a separate project or exported as a separate function.

Right now I'm using the static field from the launcher class, but that feels like something that's not part of the public API.

**Comment by patrickhulce** [comment]
thanks for filing @LarsDenBakker! The `Launcher` class pretty much *is* the public API, so I wouldn't feel nervous about using `getInstallations`. There are some private methods that you shouldn't use but if you're using typescript you should be prevented from using them anyway.

I don't think we're particularly excited about splitting this out into a separate module. Most of the dependencies we have are actually for finding chrome for `getInstallations`, so it's not like the dependency bloat would be eliminated either.

**Comment by LarsDenBakker** [comment]
@patrickhulce thanks for you answer. I'll keep using the static field then. :)
