### ISSUE TITLE
Finding installation path is sometimes slow on mac

### ISSUE THREAD

**Issue by LarsDenBakker** [GoogleChrome/chrome-launcher#207]
On my macbook pro it takes around 5 seconds to find my installation of chrome. This slows down execution of tests a lot. I asked around to some friends, and for some of them it's also this slow while for others it's fast.

I did some debugging in the code, and I think the culprit is here https://github.com/GoogleChrome/chrome-launcher/blob/master/src/chrome-finder.ts#L36 where the -dump listing is simply a lot of text. Unfortunately not something that's we can avoid.

Looking at the list of priorities here: https://github.com/GoogleChrome/chrome-launcher/blob/master/src/chrome-finder.ts#L54 I think we can speed up the lookup for the common cases by first doing a quick direct FS check fo these file paths. If they don't exist, then you can fallback on the more extensive lookup.

I can open a PR for this if this is something you think is worth adding.

**Comment by patrickhulce** [comment]
Thanks for filing @LarsDenBakker this just started happening for me locally as well! I think it might be problematic to ensure we return the same output of `getInstallations` without it but I agree something should be done for this.

**Comment by christian-bromann** [comment]
@patrickhulce do we want to always return all available Chrome apps? Otherwise we could just check for the default paths (e.g. `'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'`) and return that if found by `fs.existsSync`.

Happy to make the change if you agree with this solution.

**Comment by patrickhulce** [comment]
I think that change would be great for the default chrome-launcher path of `.launch`

i.e. we leave `getInstallations` alone but create `getFirstInstallation` that does exactly what you suggest without needing to invoke the -dump

**Comment by christian-bromann** [comment]
> i.e. we leave `getInstallations` alone but create `getFirstInstallation` that does exactly what you suggest without needing to invoke the -dump

Are you suggesting that `.launch` could take a `preferDefault` parameter that if true, checks default installation paths and returns them if found or invokes -dump if not.

**Comment by patrickhulce** [comment]
Not exactly. I was thinking of just a function kinda like

```js
function getFirstInstallation() {
  // list of the possibilities in priority order
  const defaultLocations = [
    process.env.CHROME_PATH,
    process.env.OTHER_CHROME_THING,
    '/Applications/Google Chrome.app/...',
    // ...
  ]
  for (const defaultLocation of defaultLocations) {
    if (canAccess(defaultLocation)) return defaultLocation
  } 

  return getInstallations()[0]
}
```

that launch uses so it doesn't force the evaluation of *all* the installations

**Comment by christian-bromann** [comment]
@patrickhulce made a PR #209
