### ISSUE TITLE
Debian 

### ISSUE THREAD

**Issue by yezz123** [GoogleChrome/chrome-launcher#215]
I wanna ask if i can launch or test the `Chrome-launcher` using Debian ver` 8.00 ` and NodeJs `LTS (v12.x)` i installed using  Binary Distributions.

_Packages & versions :_
```
apt: 1.0.9.8.1
kernel: Linux 3.16
gcc: 4.9
Gnome 3.14, KDE 4.14, Xfce 4.10
libc: libc6 2.19-18
X-server: Xorg 7.7
```

**Comment by patrickhulce** [comment]
We have no reason to believe that you wouldn't be able to :)
