### ISSUE TITLE
Allow Notification

### ISSUE THREAD

**Issue by RezaErfani67** [GoogleChrome/chrome-launcher#216]
thank you for this...
how can i set Notification To {Allow}?

**Comment by patrickhulce** [comment]
Thanks for filing @RezaErfani67! This library is just for *launching* Chrome, not for controlling it or accepting any permissions of a particular page once launched.

You might be interested in [puppeteer](https://github.com/puppeteer/puppeteer) though which is a little more comprehensive in this area.
