### ISSUE TITLE
open 2 instances using same userdatadir / profile

### ISSUE THREAD

**Issue by DoskJS** [GoogleChrome/chrome-launcher#220]
hello,

i've been using chrome-launcher w/ chrome devtools protocol to automate tasks.

i've ran into an issue.
whenever i try to launch a second instance, it reuses the first as a new tab.
they work fine separately

**Comment by patrickhulce** [comment]
I don't think what you're describing is possible (launching a separate Chromium instance but using the same user profile). 

Are you just trying to open a new window for the same instance? You can do that just through [the protocol on the existing instance (`newWindow: true`)](https://chromedevtools.github.io/devtools-protocol/tot/Target/#method-createTarget).

**Comment by DoskJS** [comment]
@patrickhulce thx for the quick response
a new window would also work, I just need the user data
if I open a new window, I'm unable to use cdp to control it from the port given by launcher. should I just open the window from cdp if that's possible?

**Comment by patrickhulce** [comment]
> should I just open the window from cdp if that's possible?

Yes.

> I'm unable to use cdp to control it from the port given by launcher.

You'll need to attach to that target. I suggest giving [puppeteer](https://github.com/puppeteer/puppeteer) a try if you're going to be doing anything fancy with multiple targets. It makes working with these concepts much easier :)
