### ISSUE TITLE
How to use chromeLauncher in Google App Engine Node js environment

### ISSUE THREAD

**Issue by sunildarji811** [GoogleChrome/chrome-launcher#223]
I want to use chromeLauncher with my node js application with Google App Engine Node js environment.

Currently getting error with "the environment variable chrome_path must be set to executable of a build of chromium version 54.0 or later"

**Comment by patrickhulce** [comment]
Chrome launcher needs Chrome to be installed on the system in order to be used. If you're looking for a "batteries included" library that ships with Chromium already you might be interested in [puppeteer](https://github.com/puppeteer/puppeteer).
