### ISSUE TITLE
Throw an error if the server is unavailable

### ISSUE THREAD

**Issue by bob-zs** [GoogleChrome/chrome-launcher#233]
When the server is not available, is there a way to have the process kill itself? We're using it for lighthouse tests, and we don't want to have to wait for it to run every test if the chrome-launcher fails to connect to a server in the first place.

We posted a related issue for GoogleChrome's lighthouse: 
https://github.com/GoogleChrome/lighthouse/issues/11996#issue-793663035

**Comment by patrickhulce** [comment]
chrome-launcher doesn't care about webpage navigations and servers, it just launches Chrome. Lighthouse is the place to discuss this behavior.
