### ISSUE TITLE
Connecting with IP:PORT:USER:PASS proxy

### ISSUE THREAD

**Issue by jackwicklow1** [GoogleChrome/chrome-launcher#239]
Trying to launch chrome browser with an IP:PORT proxy. I've seen instructions from here:
https://www.chromium.org/developers/design-documents/network-settings#TOC-Command-line-options-for-proxy-settings
but it does not work.
If anyone can help me launch this browser using an IP:PORT format proxy e.g. 32:125:10:108:3002, I'll pay $250.

Thanks

**Comment by patrickhulce** [comment]
What type of proxy are you using and what errors are you seeing?

You might find https://superuser.com/questions/902620/google-chrome-proxy-settings-with-username-and-password and https://bugs.chromium.org/p/chromium/issues/detail?id=615947 helpful (it's not possible to specify username and password for proxy settings from the command line, you would need a local proxy that injects the auth for your remote proxy as described in the linked superuser question)

**Comment by jackwicklow1** [comment]
Unfortunately I need it to be like how puppeteer works, where if you have a proxy IP:PORT:USER:PASS, you can use it through hard-coding.

**Comment by patrickhulce** [comment]
How do you use it through puppeteer? 

I'm not familiar with puppeteer being able to set any Chrome proxy username/password settings. You can use request interception (or a library like [puppeteer-page-proxy](https://github.com/Cuadrix/puppeteer-page-proxy)) to build your own proxy server, but there's not a way I'm aware of to set a proxy with username/password settings either through command-line flags or the CDT protocol.

**Comment by patrickhulce** [comment]
> Trying to launch chrome browser with an IP:PORT proxy.

Wait, to be clear. Are you trying to *launch* a browser that uses your specified proxy settings? Or are you trying to *connect* to an already running Chrome somewhere else that is only accessible *via a proxy*?

**Comment by jackwicklow1** [comment]
I need to launch a browser that uses the proxy. I've seen the docs that I included in my post, but they don't work. I get the error message ERR_NO_SUPPORTED_PROXIES.

**Comment by patrickhulce** [comment]
OK, chrome-launcher only handles the *launching* of Chrome. All the methods available to puppeteer from the command-line are available here, but like mentioned in https://github.com/GoogleChrome/chrome-launcher/issues/239#issuecomment-825713853, there is not a way *through command-line flags alone* to specify username and password proxy settings. Once Chrome has started you'd need to connect over the protocol and finish configuring request interception to achieve the result you're looking for (at which point, just connect with puppeteer).

**Comment by jackwicklow1** [comment]
I've tried launching chrome with chrome-launcher using a proxy, like the docs say, then connecting with puppeteer and trying to authenticate it through there, which doesn't seem to work. So the only way is to intercept all requests through puppeteer using puppeteer-page-proxy or similar?

**Comment by forklive** [comment]
mistake: "anonimizeProxy" need to be "anonymizeProxy"
