### ISSUE TITLE
Using Chrome-Launcher and Lighthouse opens two Chrome instances in incognito mode

### ISSUE THREAD

**Issue by gyh9457** [GoogleChrome/chrome-launcher#244]
When I use lighthouse to detect a website, I got a warning info : There may be stored data affecting loading performance in this location: indexedDB. Audit this page in an incognito window to prevent those resources from affecting your scores.

so I want to use incognito mode. But when  I use this mode , I find that it opens two chrome instance in the process. one is in incognito mode, and another is not in incognito .

Version:
* window10
* chrome: 92
*  chrome-launcher 0.14.0
*  lighthouse: 8.0.0

Demo:
```
const chrome = await chromeLauncher.launch({chromeFlags: [
    '--incognito', '--start-in-incognito'
  ]})
const opts = {
  output: 'json'
}
const result = await lighthouse(url, opts)
```

![image](https://user-images.githubusercontent.com/13557235/128187479-02375071-a91e-4c34-bcb4-c6e07f0c3eb8.png)

**Comment by patrickhulce** [comment]
If you're using chrome-launcher with default flags you don't need to worry about incognito. It will use a fresh chrome profile every time. 

If you got the warning message in a fresh chrome profile using chrome-launcher definitely file a bug with repro steps so we can take a look and fix it over there!

**Comment by gyh9457** [comment]
In fact, the page I want to check requires login, so I first use puppeteer to log in and then check the page.
 When I add disableStorageReset, there will be no more warnings. 
But how do I disable network cache, such as disk cache, Menory cache? I think that might have affected the results, too

@patrickhulce

**Comment by patrickhulce** [comment]
There is no way to accomplish what you want today using Lighthouse alone.

You can either...

1) Use `disableStorageReset` (which is intended for your exact use case of testing a page that can only be reached after visiting the site previously) and manually [clear your desired caches using puppeteer](https://pptr.dev/#?product=Puppeteer&version=v10.1.0&show=api-pagesetcacheenabledenabled).
2) Ignore the warnings.

**Comment by gyh9457** [comment]
Thank you for your answer  @patrickhulce
