### ISSUE TITLE
Killing chrome instance generates deprecation warning

### ISSUE THREAD

**Issue by adamreisnz** [GoogleChrome/chrome-launcher#245]
Killing a Chrome instance generates the following deprecation warning on Node 16:

`[DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead`

**Comment by smcllc** [comment]
Temporary fix: find ~/chrome-launcher/dist/chrome-launcher.js, line 286

this.fs.rmdir(this.userDataDir, { recursive: true }, () => resolve());

change to 

this.fs.rm(this.userDataDir, { recursive: true }, () => resolve());

It should go away.

**Comment by paulirish** [comment]
fixed in #242 

shipped in v0.14.2
