### ISSUE TITLE
chrome-launcher in docker can not connect success

### ISSUE THREAD

**Issue by gyh9457** [GoogleChrome/chrome-launcher#246]
I want to run lighthouse in docker. tthe docker is baseed on node:14.17.1-alpine

when  I use chrome81, chrome-launcher work fine

but chrome 81 is not support CLS, so I update chrome to 92
![image](https://user-images.githubusercontent.com/13557235/130571174-3ef873db-24e5-48cd-b92b-fa231fde8db0.png)

after upgrade, chrome-launcher can not connect success

I get the error 
![image](https://user-images.githubusercontent.com/13557235/130571099-4f28ce24-7a18-487b-9be0-aefd6707ed21.png)

in chrome-error.log, I find that:
![image](https://user-images.githubusercontent.com/13557235/130575365-a20bd560-b9ce-4acc-8d01-7b8a8c3bb341.png)

**Comment by patrickhulce** [comment]
Thanks for filing @gyh9457! 

That means that image does not have the dependencies necessary to run newer version of Chrome. 

This tracker is for issues in the `chrome-launcher` npm package, and we don't have the bandwidth support generic Chrome installation questions.
