### ISSUE TITLE
Question: Chrome launcher with cookies

### ISSUE THREAD

**Issue by dsimoes** [GoogleChrome/chrome-launcher#254]
Hi,

I'm using Lighthouse (Node) to run a perf test on a particular site.
This site will behave differently by reading in JavaScript a certain cookie value.

I managed to instruct Lighthouse to pass the cookie value and I verified in Fiddler that indeed the launched Chrome window will set the cookie value on the request header.

But when the page is rendered, it's like the cookie isn't there, meaning the JavaScript code will read the cookie as non-existent/null.

I've searched and hit a dead end.. is this a limitation of the launched Chrome? Meaning the page JS won't be able to read cookies?

Thank you for your help.

**Comment by connorjclark** [comment]
LH version / command you're using?

**Comment by dsimoes** [comment]
@connorjclark sorry, here is the additional info:

chrome-launcher@0.14.1
lighthouse@8.6.0

Code for the test:

const chrome = await chromeLauncher.launch();
const options = {logLevel: 'info', output: 'html', port: chrome.port, extraHeaders: {"Cookie": "mycookie=yes"}};
const runnerResult = await lighthouse(url, options, config);

**Comment by dsimoes** [comment]
Hi everyone,

Trying to revive this issue/question.. can anyone assist on this?

**Comment by dsimoes** [comment]
Ended up using puppeteer which allowed me to setup the cookies prior to running Lighthouse.

**Comment by wengx00** [comment]
> Hi,
> 
> I'm using Lighthouse (Node) to run a perf test on a particular site. This site will behave differently by reading in JavaScript a certain cookie value.
> 
> I managed to instruct Lighthouse to pass the cookie value and I verified in Fiddler that indeed the launched Chrome window will set the cookie value on the request header.
> 
> But when the page is rendered, it's like the cookie isn't there, meaning the JavaScript code will read the cookie as non-existent/null.
> 
> I've searched and hit a dead end.. is this a limitation of the launched Chrome? Meaning the page JS won't be able to read cookies?
> 
> Thank you for your help.

Hey man, I had this problem too and here's my solution.
1. Start the whistle proxy locally, configure the proxy rules to the target where Lighthouse is running, e.g. example.com/index.html, and inject the response cookie via resCookies://<cookie-file-path>.

> My whistle configuration is available for reference:
example.com/index.html resCookies://~/Workspace/hack-cookies.json

2. Apply whistle to the global proxy, in detail by running a two-line bash:

```bash
w2 start
w2 proxy
```

Additional, maybe you need to exec `w2 ca` to install the CA

This concludes the process.
