### ISSUE TITLE
Add support for WSL on Windows 10

### ISSUE THREAD

**Issue by molant** [GoogleChrome/chrome-launcher#26]
Starting on [build 14951](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-14951) WSL supports opening windows applications from bash. This will be available for anyone in the next stable release of Windows in [October 17th](https://blogs.windows.com/windowsexperience/2017/09/01/create-and-play-this-holiday-with-the-windows-10-fall-creators-update-coming-oct-17/)

Bash on Windows is becoming very popular and adding support to this will be great. We've had a few people run into this issue when using [sonar](https://github.com/sonarwhal/sonar).

I can probably look into adding this if no one else wants to 😊

**Comment by paulirish** [comment]
@molant yeah if you could give it a go, that'd be excellent.  our access to windows machines is pretty limited. :)

**Comment by paulirish** [comment]
Ah! well there we go. :)
