### ISSUE TITLE
sandbox utility bwrap remains open after kill or killall 

### ISSUE THREAD

**Issue by philipphutterer** [GoogleChrome/chrome-launcher#273]
I unfortunately haven't yet found anything regarding this problem.
On my linux machine (`Debian GNU/Linux bookworm/sid`) there remains a process in background after otherwise successfully closing main windows of chrome (`Chromium 97.0.4692.71` in my case) via `kill` or `killAll`:

command `bwrap --args 40 /app/chromium/chrome --type=zygote --headless`.

I consider this a bug since there will be a remaining process for each `launch` operation. Also, the process remains open beyond the lifetime of the parent process.

**Comment by connorjclark** [comment]
This seems like a chrome issue? Try crbug.com
