### ISSUE TITLE
Add ability to pass environment variables for launched Chrome process (to set TZ)

### ISSUE THREAD

**Issue by samir-mahendra** [GoogleChrome/chrome-launcher#29]
I have a use case where I need to launch Chrome with a different "TZ" variable than the one the environment is running under.

While I can do this in my launching Node process, it would make my script easier if I had a way to pass TZ into the launcher.

If you accept env as a launcher option, it would then get passed along into spawn command here: https://github.com/GoogleChrome/chrome-launcher/blob/master/chrome-launcher.ts#L220

Format of env argument could be something like this for example:

env: { 'TZ': 'America/New_York'}

**Comment by samccone** [comment]
Thanks so much for reaching out @samir-mahendra I have gone ahead and opened a PR to address this.

**Comment by paulirish** [comment]
shipped in 0.10.0
