### ISSUE TITLE
make possible to disable chrome to offer saving password in chrome-launcher

### ISSUE THREAD

**Issue by ciekawy** [GoogleChrome/chrome-launcher#32]
there was --disable-save-password-bubble which has been apparently removed: https://bugs.chromium.org/p/chromedriver/issues/detail?id=1015

also I can see no option to set prefs as suggested in the above link

**Comment by samccone** [comment]
@paulirish any thoughts on the magic bit to set for this one?

**Comment by paulirish** [comment]
Add `--enable-automation` to your `chromeFlags`. It should turn them off. 
Also that flag does a few more things: https://github.com/GoogleChrome/chrome-launcher/pull/23#discussion_r138452200

**Comment by furzimyrial** [comment]
--enable-automation
--disable-infobars

**Comment by vaibtripathi** [comment]
@furzimyrial --disable-infobars does not work for me on Chrome81. Anything else I should look at?
