### ISSUE TITLE
`chrome://extensions/` will not open as defined URL

### ISSUE THREAD

**Issue by Bizarrus** [GoogleChrome/chrome-launcher#339]
Thr URL `chrome://extensions/` will not open as defined URL.

```javascript
ChromeLauncher.launch({
    startingUrl: 'chrome://extensions/',
    chromeFlags: [
        '--load-extension=' + Path.resolve(import.meta.dirname, '../Build/chrome/'),
        '--dev',
        '--auto-open-devtools-for-tabs',
        '--enable-auto-reload'
    ]
}).then(chrome => {
    console.log(`Chrome debugging port running on ${chrome.port}`);
});
```

**Result:**
<img width="582" alt="image" src="https://github.com/user-attachments/assets/db9a6d42-62b9-4c06-8e9f-430bf4d902eb">

**Comment by Bizarrus** [comment]
Okay, seems that `Chrome` blocks generally internal URLS like `chrome://extension/`.
An redirect-Workaround will also not work and gets an `ERR_UNSAFE_REDIRECT`:

```php
<?php
	header('Location: chrome://extensions/');
?>
Try to redirect to <a href="chrome://extensions/">chrome://extensions/</a>.
```

Some other ideas to start `Chrome` with the default page `chrome://extensions/`?
I need it for a extension-development.

**Comment by paulirish** [comment]
i think the only way is with CDP.. a Page.navigate call to that URL.

Without CDP you can't automate opening protected pages like that.

But if you're going the CDP route you should just use Puppeteer or Playwright and drop chrome-launcher as they do their own launching.
G'luck!
