### ISSUE TITLE
How to listen for browser close event

### ISSUE THREAD

**Issue by ORESoftware** [GoogleChrome/chrome-launcher#39]
I see that `chrome-launcher` allows us to kill the browser. However if the browser closes itself (`window.close()` I believe it is), is there a way to listen for when the browser process ends using this library?

**Comment by ORESoftware** [comment]
Perhaps it's as simple as:

```js
chromeLauncher.launch({
  startingUrl: 'https://google.com',
  chromeFlags: ['--headless', '--disable-gpu']
}).then(chrome => {
  chrome.once('exit', handleExit); // <<<<< here
});
```

it would be nice if this were in the readme, if this is the case, thanks

**Comment by ORESoftware** [comment]
Here's the relevant PR https://github.com/GoogleChrome/chrome-launcher/pull/40

**Comment by furzimyrial** [comment]
chromeLauncher.launch({
        startingUrl: 'http://127.0.0.1:8080',
        chromeFlags: ['--kiosk','--disable-gpu']
      }).then(chrome => {
        chrome.process._handle.onexit = function () {
          //Some code here
        };
      });

**Comment by furzimyrial** [comment]
```
chromeLauncher.launch({
        startingUrl: 'http://127.0.0.1:8080',
        chromeFlags: ['--kiosk','--disable-gpu']
      }).then(chrome => {
        chrome.process._handle.onexit = function () {
          console.log('Exited');
        };
      });
```

**Comment by iongion** [comment]
Is there a way to detect close ?

**Comment by patrickhulce** [comment]
@iongion yes, #67 exposed the process instance so just use the regular [node API](https://nodejs.org/api/child_process.html#child_process_event_close).

```js
chromeLauncher.launch().then(chrome => chrome.process.on('close', console.log))
```
