### ISSUE TITLE
Force Chrome to pause at `debugger;` statements

### ISSUE THREAD

**Issue by ORESoftware** [GoogleChrome/chrome-launcher#41]
I'd like to debug Google Chrome - using this module, is there a way to force Chrome to stop at the first debugger; statement? Is there a Chrome option for that. I have a codebase littered with debugger; statements, yet Chrome won't pause at them when I launch Chrome with `chrome-launcher`.

If you want some SO points, I have this question on there:
https://stackoverflow.com/questions/46881436/force-google-chrome-to-pause-at-breakpoints-debugger-statements

thanks

**Comment by paulirish** [comment]
presumably you're using chrome-remote-interface too?  that behavior will be managed through CRI.
launcher doesn't do much

you'll have to sniff how devtools does this but i'm nearly sure its something in the Debugger domain

see sniffing on https://chromedevtools.github.io/devtools-protocol/
https://chromedevtools.github.io/devtools-protocol/tot/Debugger/

**Comment by ORESoftware** [comment]
I tried calling this before any of my `debugger;` statements

`window.Debugger.enable()`

and that didn't do anything, I will try some other things
