### ISSUE TITLE
Support question - launch browser with a predefined html page

### ISSUE THREAD

**Issue by ORESoftware** [GoogleChrome/chrome-launcher#42]
I am wondering if there is a way to launch Chrome using chrome-launcher, and have Chrome load an HTML file without having to make a request for the HTML from a server?

How can we do that? Please advise.

**Comment by shi-cong** [comment]
https://github.com/GoogleChrome/rendertron

**Comment by patrickhulce** [comment]
Yes, you can navigate to a data URI https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs. 

Keep in mind taking an arbitrary page and converting it to a data URI will likely see different behavior than when its served from a server though (relative URLs, security origin differences, etc).

**Comment by ORESoftware** [comment]
@patrickhulce  thanks - any reason we can't load an html file like you would with a request/response to a server? I just want do something like:

```js
cl.launch({
   html: 'index.html'
}, result => {});
```

**Comment by patrickhulce** [comment]
Oh do you just want to navigate to the file protocol path? This will have similar issues to data URI but you can use that path as your starting URL.

Example

```
const path = require('path')
const absolutePathToFile = path.join(__dirname, 'relative/path/to/file.html')
chromeLauncher.launch({startingUrl: 'file://' + absolutePathToFile})
```

**Comment by samccone** [comment]
@patrickhulce nailed it.

Please do let us know if you have any other questions.

Have a great day.
