### ISSUE TITLE
this vs. puppeteer - launch browser to automatically stop at breakpoints

### ISSUE THREAD

**Issue by ORESoftware** [GoogleChrome/chrome-launcher#43]
Hey all, looks like puppeteer will stop at breakpoints/debugger statements if `devTools` is set to true:

https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerlaunchoptions

Is there a way to do the same thing with chrome-launcher, or should I use puppeteer instead? I am not even sure what the difference is between `puppeteer` and `chrome-launcher`, would be nice for a brief compare and contrast in the README?

**Comment by ORESoftware** [comment]
Looks like using chrome-launcher, we can use:

this command line switch:
--auto-open-devtools-for-tabs

which I found here:
https://peter.sh/experiments/chromium-command-line-switches/

**Comment by ORESoftware** [comment]
Actually this didn't work as I hoped - I thought the browser would pause at the first `debugger;` statement, but it didn't.

**Comment by patrickhulce** [comment]
This is outside the scope of chrome launcher. To answer your question, this repository is purely for finding and launching an existing Chrome installation on your machine. Puppeteer is a high-level API for controlling Chrome using the DevTools protocol in addition to downloading a specific compatible Chromium version and launching it. Many of your use cases you seem interested in are more in the puppeteer or [cri](https://github.com/cyrus-and/chrome-remote-interface) wheelhouse.

From our perspective, the flag is passed successfully and DevTools opens as promised, but execution is not paused until DevTools is attached. Getting the behavior you desire requires more fine grained control of the browser over the protocol with puppeteer or cri.

**Comment by ORESoftware** [comment]
+1 for usage of "wheelhouse" :)

**Comment by ORESoftware** [comment]
TBH I will probably go for puppeteer first because it seems "more official" unless you think CRI is a better bet

**Comment by patrickhulce** [comment]
Yep sounds like a good plan @ORESoftware puppeteer is a great project :)
