### ISSUE TITLE
Potential bug - flag does not make browser stop at breakpoints / debugger statements

### ISSUE THREAD

**Issue by ORESoftware** [GoogleChrome/chrome-launcher#44]
re:  https://github.com/GoogleChrome/puppeteer/issues/408#issuecomment-340991045

if I use this:

```js
      cl.launch({
        startingUrl: `http://localhost:${port}/suman_testing?data=${testData}`,
        chromeFlags: ['--auto-open-devtools-for-tabs']
      })
```

this chrome flag should tell the browser to pause at the first breakpoint / debugger; statement, but it doesn't seem to do that.

My Chrome version should be relatively new, any idea what the problem might be?

**Comment by patrickhulce** [comment]
dupe of #43 let's discuss there

**Comment by ORESoftware** [comment]
uhh, I think you closed #43 , did you mean to link to a different issue?

**Comment by patrickhulce** [comment]
The comments I added to #43 explain that this is WAI. DevTools does indeed get opened, just not the behavior you want.

**Comment by ORESoftware** [comment]
WAI? sorry

**Comment by ORESoftware** [comment]
Wheelhouse Andover Inexplicable?

**Comment by patrickhulce** [comment]
Working as intended :)

**Comment by ORESoftware** [comment]
ahh thanks, good to know!
