### ISSUE TITLE
Support question - Force usage of Canary

### ISSUE THREAD

**Issue by ORESoftware** [GoogleChrome/chrome-launcher#45]
How can I tell chrome-launcher to launch the Canary version of Chrome, if I have more than one version of Chrome installed on a machine?

**Comment by patrickhulce** [comment]
Use the `chromePath` flag if you have the absolute path or `CHROME_PATH` environment variable if you have a partial path. Canary will already be preferred over stable by default on macOS. See [README](https://github.com/GoogleChrome/chrome-launcher#launchopts) or [chrome-finder.ts](https://github.com/GoogleChrome/chrome-launcher/blob/master/chrome-finder.ts) for details.

**Comment by ORESoftware** [comment]
thanks will make use of this
