### ISSUE TITLE
grep -R fails on alpine linux

### ISSUE THREAD

**Issue by danbopes** [GoogleChrome/chrome-launcher#46]
See this commit [here](https://github.com/nros/chrome-finder/commit/0afd72ee5cd2f294a0e003c25c473995db6bf80e). chrome-finder should fall back to using lowercase R on platforms that don't support uppercase R.

**Comment by AkshayIyer12** [comment]
I want to work on this @patrickhulce .

**Comment by patrickhulce** [comment]
great thanks for volunteering @AkshayIyer12!

**Comment by AkshayIyer12** [comment]
@patrickhulce I have fixed the issue locally on my system.
Do I have to also build it and check whether the tests are passing ?
The documentation is not available on building it.
And also is there a commit format for the project ?

**Comment by paulirish** [comment]
shipped in 0.10.0
