### ISSUE TITLE
How to obtain the websocket URL?

### ISSUE THREAD

**Issue by gajus** [GoogleChrome/chrome-launcher#50]
I would like to spin up multiple instances using `chrome-launcher` and then connect to them using Puppeteer. It is not clear how to obtain the websocket URL of the headless Chrome instance, e.g. `ws://127.0.0.1:9222/devtools/browser/d9f8012e-94b8-4441-ad1e-1cf8de94e57f`.

`chrome-launcher` only gives the port number. I have tried `ws://127.0.0.1:${obtained port number}`, but I am getting 404.

**Comment by gajus** [comment]
I just ended up using Puppeteer:

```js
const puppeteer = require('puppeteer');

const browser = await puppeteer.launch();

const url = browser._connection.url();

```

**Comment by alitoufighi** [comment]
I found an example by puppeteer folks showing how to find the WebSocket url from chrome-launcher [here](https://github.com/puppeteer/examples/blob/master/lighthouse/chromelauncher_puppeteer.js):

```javascript
const request = require('request');
const util = require('util');
const chromeLauncher = require('chrome-launcher');
const puppeteer = require('puppeteer');

// Launch chrome using chrome-launcher.
const chrome = await chromeLauncher.launch(opts);

// Connect to it using puppeteer.connect().
const resp = await util.promisify(request)(`http://localhost:${chrome.port}/json/version`);
const {webSocketDebuggerUrl} = JSON.parse(resp.body);
const browser = await puppeteer.connect({browserWSEndpoint: webSocketDebuggerUrl});
```
