### ISSUE TITLE
Update maxConnectionRetries default to 50 in docs

### ISSUE THREAD

**Issue by sebastianseilund** [GoogleChrome/chrome-launcher#56]
Hi there! 

`maxConnectionRetries` is documented with a default of 10 in `README.md`.

It's actual default is 50 (in `chrome-launcher.ts`).

Should the readme be updated, or should the default be adjusted? A default of 50 retries with default `connectionPollInterval` of 500ms seems like a really long time.

**Comment by patrickhulce** [comment]
Ah good catch @sebastianseilund we should update the docs! 👍 

It was bumped to 50 after finding that 10 and 500ms was a bit too optimistic when running on low-end hardware/multi-tenant server environments. Seems reasonable to make sure the majority of cases can be started without changing options, but if you are encountering real failures for some other reason feel free to pass in a lower value if you'd prefer to fail fast.
