### ISSUE TITLE
Bikeshed changing default chrome flags used.

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/chrome-launcher#65]
Breaking this out from #38 where we explored this the most. cc @ragingwind 

Here is the node module API implemented in #38 (let's call this _JS vAlpha API_):
```js
chromeLauncher.defaultFlags() // array of all the flags it uses by default

chromeLauncher.launch({
  ignoreDefaultFlags: true,  // will not supply any defaults.. the ones passed in below are it.
  chromeFlags: [] // array of the only flags to use
});
```

and a _CLI vAlpha API_:
```sh
chrome-launcher --list-flags # prints and quits: '--disable-extensions --disable-translate-service ....'

chrome-launcher # launches with default flags
chrome-launcher --set-flags="--show-paint-rects --disable-extensions"   # skips default flags and only uses provided ones
# naming: maybe "override-flags" to indicate this may break things..

# also allow just augmenting default flags with --add-flags
chrome-launcher --add-flags="--show-paint-rects"
# (this behavior is what lighthouse's current --chrome-flags arg does)
```

**Comment by samccone** [comment]
What about the required flags that we need to run chrome-launcher? Such as the remote debugging port and user dir?

**Comment by paulirish** [comment]
As discussed with @samccone here's a (_CLI vBeta_):

```sh
launch-chrome --flags="--no-disable-extensions"    
```

Essentially, inside of the flags string, look for the `no-` prefix and if found, remove those from the default flags list.

**Comment by paulirish** [comment]
> What about the required flags that we need to run chrome-launcher? Such as the remote debugging port and user dir?

Good Q. IMO they shouldn't be able to unset the remote-debugging-port one. Puppeteer and Chrome-launcher both keep that one a little protected.

In #49 we added support to allow default user-data-dir and not even set it. That could have been done through this proposal rather than a `forceDefaultProfile` option in the API. Probably makes more sense to use this proposal, instead of the one-off, yah.

**Comment by paulirish** [comment]
As discussed with @patrickhulce here's a _JS vGamma_:

```js
const flags = chromeLauncher.defaultFlags() // Map of all the flags it uses by default

flags.delete('--disable-extensions');
flags.delete('--mute-audio');
flags.set('--user-data-dir', somepath);

chromeLauncher.launch({chromeFlags: flags});
```

And we'd use a little duck typing:
* If chromeFlags is an array, add the results on to the default flags.
* If chromeFlags is a map, do not apply default flags and only use the provided ones (plus remote-debugging-port).

**Comment by paulirish** [comment]
Discussed with konrad and patrick and they favored _CLI vAlpha API_  and _JS vGamma API_.
They thought _CLI vBeta API_ had too much magic and requires a lot of explanation.

**Comment by Gudahtt** [comment]
Ignoring a single flag seems like a fairly common use case (e.g. the mute-audio flag, as in the linked issue). That case is better served by allowing a single flag to be ignored. It also makes sense to have a flag to ignore all flags, in case the user wants complete control.

Both of these cases are served fairly well by the current JS API. All of the CLI proposals are wanting though.

_CLI vAlpha API_ makes it difficult to ignore a single flag. It would require calling `chrome-launcher --list-flags`, removing one flag, then calling `chrome-launcher` again.

_CLI vBeta API_ and _CLI vGamma API_ both deal with ignoring a single flag well, but they make it inconvenient to ignore all flags.

Something like _CLI vGamma API_ or _CLI vBeta API_ with the addition of `--ignore-default-flags` would serve all cases fairly well though.

I did notice that there is no `chrome-launcher` CLI though. Perhaps this issue can be closed?

**Comment by patrickhulce** [comment]
Yes @Gudahtt I believe we consider this resolved by https://github.com/GoogleChrome/chrome-launcher/pull/124. We can revisit a future date if there becomes a stronger need.
