### ISSUE TITLE
docs improvement - open new tab or window

### ISSUE THREAD

**Issue by ORESoftware** [GoogleChrome/chrome-launcher#76]
in the readme, it doesn't look like there is an option to open a new window in chrome or just a new tab

last time I looked in the codebase, I believe it defaults to opening a new tab (it tries it's best to).

is there some flag to force opening a new window? should that be documented?

**Comment by paulirish** [comment]
Hmmm. Not clear what you're asking for. 

I believe in all OS's the current behavior is to launch a single new window with a tab of the provided URL.

What difference in behavior are you asking for?

**Comment by ORESoftware** [comment]
is there a way to open a new tab in an existing window?

**Comment by paulirish** [comment]
[Target.createTarget](https://chromedevtools.github.io/devtools-protocol/tot/Target/#method-createTarget) in the protocol.

**Comment by ORESoftware** [comment]
Paul that is really cool - my point with this issue is this surely must be a common need and it should go in the readme, no??

**Comment by patrickhulce** [comment]
@ORESoftware there seems to be some confusion around the goals of chrome-launcher which is just to launch the Chrome browser as opposed to control/instruct the browser to do things which is the goal of projects like [puppeteer](https://github.com/GoogleChrome/puppeteer).

**Comment by ORESoftware** [comment]
ok guys, I am not sure what I a missing here - it's clear that many users will want to launch the browser, either in a new window, or as a tab in an existing window. All I am talking about is allowing the user to control whether the new browser is launched as a tab in existing window or new window...

**Comment by patrickhulce** [comment]
Perhaps the confusion is the concept of "launched as a tab in existing window". 

If you already have Chrome launched, I'm not sure why you need chrome-launcher? You already have completed the only step that chrome-launcher helps you with. Connect to the existing Chrome instance with puppeteer/websocket/CRI/whatever and create a new target.

**Comment by paulirish** [comment]
@ORESoftware chrome-launcher on its own doesn't do much. it gets the executable running and exposes the remote debugging port.   interaction beyond that MUST be done with the protocol, typically through either chrome-remote-interface or with puppeteer. 

I could imagine there's a line in the readme like:

> Interacting with or controlling the page or browser must be done with the devtools protocol, typically via chrome-remote-interface. (Puppeteer is also good, but has it's own chrome launching mechanism).

**Comment by ORESoftware** [comment]
ok thanks, I guess I am indeed missing some information, thanks for the info, I haven't tried puppeteer yet, but I guess I should
