### ISSUE TITLE
Fails to find Chrome on Windows 10 latest, x64 in certain cases

### ISSUE THREAD

**Issue by janpieterz** [GoogleChrome/chrome-launcher#86]
Interestingly, using the same chrome-launcher, it seems like in certain running scenario's it fails to find Chrome. I encounter this using chromeless to create automated tests.

I've narrowed the cause down to https://github.com/GoogleChrome/chrome-launcher/blob/master/src/chrome-finder.ts#L170

If I change this on my local version to below it is solved. This is interesting mostly because ENV variables are supposed to be case sensitive on Windows and therefore Node.
```js
const prefixes = [
    process.env.LOCALAPPDATA,
    process.env.LocalAppData,
    process.env.PROGRAMFILES,
    process.env.ProgramFiles,
    process.env["PROGRAMFILES(X86)"],
    process.env["ProgramFiles(x86)"]
  ].filter(Boolean);
```

I'm running node v8.9.4. The differences are in one case I call `node index.js` which starts a process, in the failing case I use the `jest` test runner. Both report the platform being win32 and end up in that part, I've got no clue how to find out where the issue would lie that suddenly makes the process.env.X accessing case sensitive.

**Comment by janpieterz** [comment]
I've created a reproduction: https://github.com/janpieterz/find-chrome-issue

`npm start` works, `npm test` fails.

Difference ends up being the above prefixes array does _not_ contain the PROGRAMFILES/PROGRAMFILES(X86) folders.

This is present on:
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.16299 N/A Build 16299

**Comment by samccone** [comment]
@janpieterz I wonder if jest is doing something somewhere in their pipeline that might be changing things. I recommend opening a parallel issue on jest so that they can weigh in.

Thanks for the bug report!

**Comment by janpieterz** [comment]
This certainly seems to be an issue with Jest as seen on that thread. I've changed my local chrome-launcher to, for now, be able to run these tests locally.

For future reference, Jest launching test processes makes the `env` object lose it's special case insensitivity.
