### ISSUE TITLE
remove --disable-translate flag

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/chrome-launcher#88]
--disable-translate hasn't been a thing for a while now, we can get rid of it from our default flags

**Comment by rokobuljan** [comment]
When opening in kiosk mode it's pretty annoying to see translation suggestions. Why is the flag been removed?

**Comment by paulirish** [comment]
FWIW it looks like Chromium may not have translate enabled, so using that rather than Chrome may be a workaround. I don't know of a decent solution currently, aside from that. 

I agree it sucks the flag was removed without a decent alternative.
