### ISSUE TITLE
support question - closest thing in Firefox world

### ISSUE THREAD

**Issue by ORESoftware** [GoogleChrome/chrome-launcher#89]
I did some research, the closest thing I could find to `chrome-launcher` for Firefox is the `node-firefox` library. My question is - if I want to launch Firefox the way I launch Chrome with chrome-launcher, do you know of a good tool to use? In my app I need to support both Firefox and Chrome. Thanks!

**Comment by samccone** [comment]
I do own https://www.npmjs.com/package/firefox-launcher :)
If you are interested in working on the project let me know!

**Comment by ORESoftware** [comment]
cool, sure, I may do that - what I need to do is launch some tests in the browser, I don't really need to control the browser remotely. So I don't need puppeteer for Firefox, I just need chrome-launcher for Firefox.

**Comment by paulirish** [comment]
Right now the closest project I know of is https://github.com/karma-runner/karma-firefox-launcher , though I think it's not trying to be general purpose.

But it seems like it would mostly work.

**Comment by ORESoftware** [comment]
@samccone I think a good start for firefox-launcher would be a readme and a contributing.md...if you create those I would gladly start contributing to that

**Comment by ORESoftware** [comment]
@paulirish thanks will check it out, I might just lift some of the code from that project and create something for my own use, we'll see

**Comment by samccone** [comment]
I am going to close this as it is not a chrome-launcher question. We can continue to talk here though.

**Comment by ORESoftware** [comment]
@samccone does firefox-launcher allow users to launch different versions of firefox?
