### ISSUE TITLE
Option to use different Chrome versions + store Chrome executables in central place

### ISSUE THREAD

**Issue by the1mills** [GoogleChrome/chrome-launcher#90]
So I am not sure how it currently works but

It would be nice if we could tell chrome-launcher which version of Chrome to use.

And if different versions of Chrome are bundled with chrome-launcher it would be high time to consider the simple possibility of storing all the Chrome versions in a single location on the user's disk.

A simple way to do that would be to create a directory in user $HOME

```

.chromelauncher/
       chrome-versions/
   
```

Then when you launch the child process set the $PATH variable to use the versions directory first.

This will work well.

**Comment by samccone** [comment]
Chrome launcher does not ship with any bundled chrome versions.
If you would like to launch a specific chrome instance your best option is to specify the path to the chrome bin on your disk in the launch options.

https://github.com/GoogleChrome/chrome-launcher#launchopts

**Comment by the1mills** [comment]
ahh yes, I think I was getting confused between Puppeteer and Chrome-Launcher
