### ISSUE TITLE
Very fun support question - open "blank" page with Chrome

### ISSUE THREAD

**Issue by ORESoftware** [GoogleChrome/chrome-launcher#94]
Sorry to bug you guys, but I figure you might know the answer:

https://stackoverflow.com/questions/48679549/load-empty-webpage-with-chrome-without-using-aboutblank

I am launching Chrome using the programmatic API, and I am looking to create a new tab, but not load an HTTP page, but some form of blank page. Using `about:blank` is giving me issues.

**Comment by paulirish** [comment]
looks like you got an answer over there.

a URI like `"data:text/html,<p></p>"` also works for chrome-launcher/protocol work, but the `chrome.debugger.sendCommand` (nor executeScript) will run on it.
