### ISSUE TITLE
Locale

### ISSUE THREAD

**Issue by thpoiani** [GoogleChrome/chrome-launcher#98]
Hello guys. How can I define a locale/lang?
Thanks

**Comment by patrickhulce** [comment]
probably looking for the `--lang` flag? see [chrome docs](https://developer.chrome.com/extensions/i18n#locales-testing) for help

```js
const chromeLauncher = require('chrome-launcher');

chromeLauncher.launch({
  startingUrl: 'https://google.com',
  chromeFlags: ['--lang=es']
}).then(chrome => {
  console.log(`Chrome debugging port running on ${chrome.port}`);
});

**Comment by samccone** [comment]
Closing this issue. @thpoiani let us know if this was not the answer you were looking for.

Thanks!
